### ISSUE TITLE
the purpose of the project is not clear

### ISSUE THREAD

**Issue by yegor256** [egis/gradle-build#2]
The purpose of this project is not clear enough from the `README.me` file. We have to elaborate a bit more there, to answer these questions:
- who is the main user (other projects?)
- what is the main use case?
- any quality/performance/load/etc requirements?

Ideally, this text file should comply with these requirements: http://www.yegor256.com/2014/10/20/how-we-write-product-vision.html

**Comment by moshloop** [comment]
I am not sure we want to continue with gradle at all - what are your thoughts?
Our goals is to have a common, reusable build script across all our java/groovy
based projects that supports out of the box:
1) Building, compiling and testing java and groovy code 2) Creating a jar file, embedding git info into the manifest and publishing to
a repository 3) Separating build and test dependencies - i.e. test dependencies are not
deployed to production and test classes should not leak into production code,
dependencies can be public and commercial jar files 4) Separate internal and vs external api - Multiple modules can compile against
the API of imported modules only - importing internal API's should be a compile
error

Non functional requirements:
1) Serverless - no internal hosting of maven repository etc.. Hosted bintray is
an option of final resort. 2) Fast, Builds happen often they need to be quick 3) Easy to maintain, updating the build tools to add additional steps fix bugs
shouldn't require updating each repository
We have historically used ant and found it very fast e.g.
https://gist.github.com/Egis-Moshe/eb1c47baf444ced629efe3da990e0cde
And we started migrating to Gradle for newer builds - but speed has been a
concern.
Considering a lightweight maven wrapper and Gant for the heavy lifting
https://gist.github.com/Egis-Moshe/75d477e9826f617cd115ede46007ffcc

On Mon, Jun 27, 2016 8:47 PM, Yegor Bugayenko notifications@github.com wrote:
The purpose of this project is not clear enough from the README.me file. We have to elaborate a bit more there, to answer these questions:
- who is the main user (other projects?)
- what is the main use case?
- any quality/performance/load/etc requirements?

Ideally, this text file should comply with these requirements: http://www.yegor256.com/2014/10/20/how-we-write-product-vision.html

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub , or mute the thread .

Moshe

**Comment by yegor256** [comment]
@Egis-Moshe looks like you don't need Gradle and you don't need to call it a plugin. Instead, I would turn it into a parent Maven POM, which will do everything you just explained. I think this project has to renamed to "egis/parent". All other projects will just inherit all configuration from this one. This is how we do it in `jcabi/*` projects. This is the parent one: https://github.com/jcabi/jcabi-parent (pay attention how big is the `pom.xml`). This is one of the child projects: https://github.com/jcabi/jcabi-http/blob/master/pom.xml (pay attention how relatively small is its `pom.xml`)

**Comment by yegor256** [comment]
@Egis-Moshe I think I have to understand the full picture before we can properly define the purpose of this particular module. Can you list all Java projects that you have and how they depend on each other (briefly)? Do I have access to all of them?
