### ISSUE TITLE
Location of docs

### ISSUE THREAD

**Issue by moshloop** [egis/gradle-build#4]
@yegor256 where do you think some of these docs: 
https://github.com/egis/PT/tree/master/Docs
and a glossary should be?

**Comment by moshloop** [comment]
- eslint, intelliJ settings, etc..

**Comment by yegor256** [comment]
@Egis-Moshe let's keep it where they are, for now. ideally, each project must have its own documentation and in just one file (README). projects must be independent from each other, since there is no guarantee that the same team will work on all projects. let's make sure this project is properly documented/organized and then will transfer that structure to all others.

**Comment by yegor256** [comment]
@Egis-Moshe close the ticket if the question is answered pls
